# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1c9cdb815ae25b0b6b07ce16a8dc2b3"
name = "discountTag"
handle = "discounttag"
application_url = "https://cdt-crucial-bunch-play.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "discountstag.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://cdt-crucial-bunch-play.trycloudflare.com/auth/callback",
  "https://cdt-crucial-bunch-play.trycloudflare.com/auth/shopify/callback",
  "https://cdt-crucial-bunch-play.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
